// Auto-generated by generate-manifest.ps1 — do not edit by hand.
const galleries = [
    {
        "folder":  "construction-images",
        "title":  "Construction Site Walkthrough",
        "description":  "Sample scenario showcasing daily progress photos from a construction project.",
        "images":  [
                       "construction-images/Image_01.jpg",
                       "construction-images/Image_02.jpg",
                       "construction-images/Image_03.jpg",
                       "construction-images/Image_04.jpg",
                       "construction-images/Image_05.jpg",
                       "construction-images/Image_06.jpg",
                       "construction-images/Image_07.jpg",
                       "construction-images/Image_08.jpg"
                   ]
    },
    {
        "folder":  "project-intelligence-engine",
        "title":  "Project Intelligence Engine",
        "description":  "Structured retrospective analysis on the documents your delivery teams already produce. Three AI skills: - Change Event Extraction - Root Cause Analysis - Timeline Dashboard Run against a SharePoint project site to surface causal chains, intervention windows, and early warning signals.",
        "images":  [
                       "project-intelligence-engine/00 - Intro.png",
                       "project-intelligence-engine/01 - Project Atlas.png",
                       "project-intelligence-engine/02 - Status Report.png",
                       "project-intelligence-engine/03 - Data Profiling Report.png",
                       "project-intelligence-engine/03.5 - Data Profiling Red Flkgs.png",
                       "project-intelligence-engine/04 - Discovery Workshop.png",
                       "project-intelligence-engine/05 - Change Event Extraction.png",
                       "project-intelligence-engine/06 - Change Event Log.png",
                       "project-intelligence-engine/07 - Root cause analysis skill.png",
                       "project-intelligence-engine/08 - Root cause analysis report.png",
                       "project-intelligence-engine/09 - TImeline dashboard skill.png",
                       "project-intelligence-engine/10 - Project Intelligence Dashboard.png",
                       "project-intelligence-engine/11 - Dashboard with root cause.png",
                       "project-intelligence-engine/12 - Dashboard with Governance gaps.png",
                       "project-intelligence-engine/13 - Signal Trail Timeline.png",
                       "project-intelligence-engine/14 - Dashboard with Recommendation.png"
                   ]
    }
];

