// Auto-generated by generate-manifest.ps1 — do not edit by hand.
const galleries = [
    {
        "folder":  "custom-image-tagger",
        "title":  "Custom Image Tagger",
        "description":  "A custom image tagging solution for identifying and categorizing images in your media library.",
        "images":  [
                       "custom-image-tagger/0 - Initiate Image Tagging.png",
                       "custom-image-tagger/01- Updating columns.png",
                       "custom-image-tagger/02 - Tagged images.png",
                       "custom-image-tagger/03 - Search Experience.png",
                       "custom-image-tagger/04 - Copilot Filtering with background objects.png"
                   ]
    },
    {
        "folder":  "invoice-po-reconciliation",
        "title":  "Invoice-PO Reconciliation",
        "description":  "A solution for reconciling invoices with purchase orders.",
        "images":  [
                       "invoice-po-reconciliation/00 - PO Columns.png",
                       "invoice-po-reconciliation/01 - PO Columns Extracted.png",
                       "invoice-po-reconciliation/02 - Invoice Columns.png",
                       "invoice-po-reconciliation/03 - Invoice columns extracted.png",
                       "invoice-po-reconciliation/04 - Reconcile selected invoices.png",
                       "invoice-po-reconciliation/05 - Reconciliation Complete.png",
                       "invoice-po-reconciliation/06 - Create tracking dashboard view.png",
                       "invoice-po-reconciliation/07 - Tracking dashboard complete.png",
                       "invoice-po-reconciliation/08 - Create Livelink HTML.png",
                       "invoice-po-reconciliation/09 - Live HTML dashboard.png"
                   ]
    },
    {
        "folder":  "project-intelligence-engine",
        "title":  "Project Intelligence Engine",
        "description":  "Structured retrospective analysis on the documents your delivery teams already produce. Three AI skills: - Change Event Extraction - Root Cause Analysis - Timeline Dashboard Run against a SharePoint project site to surface causal chains, intervention windows, and early warning signals.",
        "images":  [
                       "project-intelligence-engine/00 - Intro.png",
                       "project-intelligence-engine/01 - Project Atlas.png",
                       "project-intelligence-engine/02 - Status Report.png",
                       "project-intelligence-engine/03 - Data Profiling Report.png",
                       "project-intelligence-engine/03.5 - Data Profiling Red Flkgs.png",
                       "project-intelligence-engine/04 - Discovery Workshop.png",
                       "project-intelligence-engine/05 - Change Event Extraction.png",
                       "project-intelligence-engine/06 - Change Event Log.png",
                       "project-intelligence-engine/07 - Root cause analysis skill.png",
                       "project-intelligence-engine/08 - Root cause analysis report.png",
                       "project-intelligence-engine/09 - TImeline dashboard skill.png",
                       "project-intelligence-engine/10 - Project Intelligence Dashboard.png",
                       "project-intelligence-engine/11 - Dashboard with root cause.png",
                       "project-intelligence-engine/12 - Dashboard with Governance gaps.png",
                       "project-intelligence-engine/13 - Signal Trail Timeline.png",
                       "project-intelligence-engine/14 - Dashboard with Recommendation.png"
                   ]
    },
    {
        "folder":  "rfp-proposal-engine",
        "title":  "RFP Generation \u0026 Review Engine",
        "description":  "A solution for automatically generating Request for Proposals (RFPs) based on predefined templates and project requirements.",
        "images":  [
                       "rfp-proposal-engine/00 - RFP Process.png",
                       "rfp-proposal-engine/01 - RFP Review.png",
                       "rfp-proposal-engine/02 - RFP Tracker.png",
                       "rfp-proposal-engine/03 - RFP Content Sourcing.png",
                       "rfp-proposal-engine/04 - Response  Generation.png",
                       "rfp-proposal-engine/05 - Review Cascade.png",
                       "rfp-proposal-engine/06 - Summary.png"
                   ]
    }
];

