# Scans subfolders for images and merges metadata from manifest.json,
# writing galleries.js for the offline gallery app.
# Re-run whenever folders, images, or manifest.json change.

$root     = Split-Path -Parent $MyInvocation.MyCommand.Path
$exts     = @('.jpg', '.jpeg', '.png', '.gif', '.bmp', '.webp')
$manifest = @{}

$manifestPath = Join-Path $root 'manifest.json'
if (Test-Path $manifestPath) {
    try {
        $json = Get-Content -Raw -Path $manifestPath | ConvertFrom-Json
        foreach ($prop in $json.PSObject.Properties) {
            $manifest[$prop.Name] = $prop.Value
        }
        Write-Host "Loaded manifest.json with $($manifest.Keys.Count) entry(ies)."
    } catch {
        Write-Warning "Could not parse manifest.json: $_"
    }
} else {
    Write-Host "No manifest.json found; using folder names as titles."
}

$galleries = @()

Get-ChildItem -Path $root -Directory | Sort-Object Name | ForEach-Object {
    $folder = $_
    $images = Get-ChildItem -Path $folder.FullName -File |
        Where-Object { $exts -contains $_.Extension.ToLower() } |
        Sort-Object Name |
        ForEach-Object { "$($folder.Name)/$($_.Name)" }

    if ($images.Count -eq 0) { return }

    $meta        = $manifest[$folder.Name]
    $title       = if ($meta -and $meta.title)       { [string]$meta.title }       else { $folder.Name }
    $description = if ($meta -and $meta.description) { [string]$meta.description } else { "" }

    $galleries += [PSCustomObject]@{
        folder      = $folder.Name
        title       = $title
        description = $description
        images      = @($images)
    }
}

$jsonOut = $galleries | ConvertTo-Json -Depth 5
if ($galleries.Count -eq 1) { $jsonOut = "[`n$jsonOut`n]" }

$out = "// Auto-generated by generate-manifest.ps1 — do not edit by hand.`nconst galleries = $jsonOut;`n"
$outPath = Join-Path $root 'galleries.js'
Set-Content -Path $outPath -Value $out -Encoding UTF8

Write-Host "Wrote $outPath with $($galleries.Count) gallery(ies)."
